name: CI

on:
  push:
    paths:
      - 'my_career_report/**/*.json'
      - 'my_career_report/charts/**'
      - 'my_career_report/templates/**'
      - 'my_career_report/generate_report.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: |
          pip install -r my_career_report/requirements.txt
          npm install --silent
        working-directory: my_career_report
      - name: Generate report
        run: python my_career_report/generate_report.py
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: my_career_report/dist/report.pdf

